name: Run tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install_python
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y python3-dev python3-pip python3-venv libxml2-dev libxslt-dev zlib1g-dev
          # Upgrade to latest meson and ninja
          sudo pip install --upgrade meson ninja

      # needs fenics only to run test_poisson_nernst_planck_solver_fenics
      - name: install_fenics
        run: |
          sudo apt-get install -y --no-install-recommends software-properties-common
          sudo add-apt-repository -y ppa:fenics-packages/fenics
          sudo apt-get update -qy
          sudo apt-get install -y fenics python3-dolfin python3-mshr

      - name: build_c
        run: |
          sudo pip install .[test]

      - name: pytest
        run: |
          cd tests
          pytest -v --junitxml=report.xml --durations=20

      - name: report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "**/report.xml"
